// Все строки интерфейса — в одном месте.
export const STR = {
  title: 'ПОГРАНИЧЬЕ',
  subtitle: 'кооп-шутер в живом мире',
  enterName: 'Введи имя:',
  connect: 'В игру',
  connecting: 'Подключение…',
  disconnected: 'Соединение потеряно. Обнови страницу.',
  dead: 'Ты пал. Союзник может поднять тебя (E).',
  respawnIn: (s) => `Возрождение через ${s}…`,
  revive: 'Поднять союзника (E)',
  reviving: 'Поднимаю…',
  hpLabel: 'ЗД',
  hungerLabel: 'Сытость',
  ammoInf: '∞',
  reloading: 'Перезарядка…',
  pickup: (name) => `Подобрано: ${name}`,
  pickupWeapon: (name) => `Новое оружие: ${name}`,
  repDown: (f) => `Репутация с «${f}» упала`,
  repUp: (f) => `Репутация с «${f}» выросла`,
  questNew: (t) => `Новый квест: ${t}`,
  questDone: (t) => `Квест выполнен: ${t}`,
  coins: 'монет',
  talkHint: 'Говорить (E)',
  enterDungeon: 'Войти (E)',
  exitDungeon: 'Выйти (E)',
  openChest: 'Открыть (E)',
  campfireHint: 'Костёр: крафт (E)',
  roomSealed: 'Двери запечатаны!',
  roomCleared: 'Комната зачищена',
  bossDefeated: (n) => `${n} повержен!`,
  night: 'Наступает ночь…',
  morning: 'Рассвет',
  hungry: 'Ты голоден! Съешь что-нибудь.',
  starving: 'Ты умираешь от голода!',
  craft: 'Крафт',
  close: 'Закрыть',
  inventory: 'Инвентарь',
  buy: 'Купить',
  bye: 'Уйти',
  notEnoughCoins: 'Не хватает монет',
  questAccept: 'Взять квест',
  questTurnIn: 'Сдать квест',
  rumor: 'Что слышно?',
  controls: 'WASD — движение, ЛКМ — атака, Пробел/ПКМ — перекат, R — перезарядка, E — действие, 1-4 — оружие, Tab — инвентарь, C — персонаж, M — карта',
};

export const ITEM_NAMES = {
  coin: 'Монета', meat: 'Сырое мясо', cooked_meat: 'Жареное мясо',
  bread: 'Хлеб', bandage: 'Бинт', ammo_arrow: 'Стрелы',
  ammo_bolt: 'Болты', ammo_mana: 'Кристаллы маны', ammo_knife: 'Метательные ножи',
  ammo_bomb: 'Бомбы', wood: 'Древесина', hide: 'Шкура', herb: 'Травы',
  metal: 'Металл',
};
